id: IFC4D7C7A
legacy_id: P003285
ocr_import_info:
  bdrc_scan_id: W23849
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T21:41:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T04:50:38.249005+00:00'
last_modified: 2022-09-02 12:50:54.413880
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23849
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23849
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པའི་རྒྱན།
  author: རིག་པའི་དབང་ཕྱུག་དགེ་བ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9188769544696767
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1CZ2530:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2530
      total_pages: 472
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2530.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9188769544696767
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
